-- Seed data for profile reference tables

-- Roles
INSERT INTO roles (name) VALUES
  ('Software Engineer'),
  ('Frontend Developer'),
  ('Backend Developer'),
  ('Full Stack Developer'),
  ('AI Engineer'),
  ('Data Analyst'),
  ('Data Scientist'),
  ('DevOps Engineer'),
  ('Cyber Security Analyst'),
  ('Machine Learning Engineer'),
  ('Cloud Architect'),
  ('Android Developer'),
  ('iOS Developer'),
  ('Mobile Developer'),
  ('QA Engineer'),
  ('Software Development Engineer in Test'),
  ('Systems Engineer'),
  ('Network Engineer'),
  ('Database Administrator'),
  ('Product Manager'),
  ('Technical Support Engineer'),
  ('Site Reliability Engineer'),
  ('Blockchain Developer'),
  ('Game Developer'),
  ('Embedded Systems Engineer')
ON CONFLICT (name) DO NOTHING;

-- Skill categories
INSERT INTO skill_categories (name) VALUES
  ('Programming Languages'),
  ('Frontend'),
  ('Backend'),
  ('Databases'),
  ('Cloud'),
  ('DevOps'),
  ('AI/ML'),
  ('Cyber Security'),
  ('Testing'),
  ('Mobile Development'),
  ('Tools'),
  ('Soft Skills')
ON CONFLICT (name) DO NOTHING;

-- Skills
INSERT INTO skills (name, category_id) VALUES
  ('JavaScript', (SELECT id FROM skill_categories WHERE name = 'Programming Languages')),
  ('Python', (SELECT id FROM skill_categories WHERE name = 'Programming Languages')),
  ('Java', (SELECT id FROM skill_categories WHERE name = 'Programming Languages')),
  ('C++', (SELECT id FROM skill_categories WHERE name = 'Programming Languages')),
  ('C#', (SELECT id FROM skill_categories WHERE name = 'Programming Languages')),
  ('TypeScript', (SELECT id FROM skill_categories WHERE name = 'Programming Languages')),
  ('Go', (SELECT id FROM skill_categories WHERE name = 'Programming Languages')),
  ('Rust', (SELECT id FROM skill_categories WHERE name = 'Programming Languages')),
  ('Swift', (SELECT id FROM skill_categories WHERE name = 'Programming Languages')),
  ('Kotlin', (SELECT id FROM skill_categories WHERE name = 'Programming Languages')),
  ('Ruby', (SELECT id FROM skill_categories WHERE name = 'Programming Languages')),
  ('PHP', (SELECT id FROM skill_categories WHERE name = 'Programming Languages')),
  ('SQL', (SELECT id FROM skill_categories WHERE name = 'Programming Languages')),
  ('React', (SELECT id FROM skill_categories WHERE name = 'Frontend')),
  ('Angular', (SELECT id FROM skill_categories WHERE name = 'Frontend')),
  ('Vue.js', (SELECT id FROM skill_categories WHERE name = 'Frontend')),
  ('Next.js', (SELECT id FROM skill_categories WHERE name = 'Frontend')),
  ('HTML', (SELECT id FROM skill_categories WHERE name = 'Frontend')),
  ('CSS', (SELECT id FROM skill_categories WHERE name = 'Frontend')),
  ('Tailwind CSS', (SELECT id FROM skill_categories WHERE name = 'Frontend')),
  ('Bootstrap', (SELECT id FROM skill_categories WHERE name = 'Frontend')),
  ('Redux', (SELECT id FROM skill_categories WHERE name = 'Frontend')),
  ('Node.js', (SELECT id FROM skill_categories WHERE name = 'Backend')),
  ('Express.js', (SELECT id FROM skill_categories WHERE name = 'Backend')),
  ('Django', (SELECT id FROM skill_categories WHERE name = 'Backend')),
  ('Flask', (SELECT id FROM skill_categories WHERE name = 'Backend')),
  ('Spring Boot', (SELECT id FROM skill_categories WHERE name = 'Backend')),
  ('ASP.NET', (SELECT id FROM skill_categories WHERE name = 'Backend')),
  ('FastAPI', (SELECT id FROM skill_categories WHERE name = 'Backend')),
  ('REST API', (SELECT id FROM skill_categories WHERE name = 'Backend')),
  ('GraphQL', (SELECT id FROM skill_categories WHERE name = 'Backend')),
  ('PostgreSQL', (SELECT id FROM skill_categories WHERE name = 'Databases')),
  ('MySQL', (SELECT id FROM skill_categories WHERE name = 'Databases')),
  ('MongoDB', (SELECT id FROM skill_categories WHERE name = 'Databases')),
  ('Redis', (SELECT id FROM skill_categories WHERE name = 'Databases')),
  ('Firebase', (SELECT id FROM skill_categories WHERE name = 'Databases')),
  ('AWS', (SELECT id FROM skill_categories WHERE name = 'Cloud')),
  ('Azure', (SELECT id FROM skill_categories WHERE name = 'Cloud')),
  ('Google Cloud', (SELECT id FROM skill_categories WHERE name = 'Cloud')),
  ('Docker', (SELECT id FROM skill_categories WHERE name = 'DevOps')),
  ('Kubernetes', (SELECT id FROM skill_categories WHERE name = 'DevOps')),
  ('Jenkins', (SELECT id FROM skill_categories WHERE name = 'DevOps')),
  ('GitHub Actions', (SELECT id FROM skill_categories WHERE name = 'DevOps')),
  ('Terraform', (SELECT id FROM skill_categories WHERE name = 'DevOps')),
  ('Ansible', (SELECT id FROM skill_categories WHERE name = 'DevOps')),
  ('CI/CD', (SELECT id FROM skill_categories WHERE name = 'DevOps')),
  ('TensorFlow', (SELECT id FROM skill_categories WHERE name = 'AI/ML')),
  ('PyTorch', (SELECT id FROM skill_categories WHERE name = 'AI/ML')),
  ('Scikit-learn', (SELECT id FROM skill_categories WHERE name = 'AI/ML')),
  ('Pandas', (SELECT id FROM skill_categories WHERE name = 'AI/ML')),
  ('NumPy', (SELECT id FROM skill_categories WHERE name = 'AI/ML')),
  ('NLP', (SELECT id FROM skill_categories WHERE name = 'AI/ML')),
  ('Computer Vision', (SELECT id FROM skill_categories WHERE name = 'AI/ML')),
  ('LLMs', (SELECT id FROM skill_categories WHERE name = 'AI/ML')),
  ('Penetration Testing', (SELECT id FROM skill_categories WHERE name = 'Cyber Security')),
  ('Network Security', (SELECT id FROM skill_categories WHERE name = 'Cyber Security')),
  ('Ethical Hacking', (SELECT id FROM skill_categories WHERE name = 'Cyber Security')),
  ('JUnit', (SELECT id FROM skill_categories WHERE name = 'Testing')),
  ('Selenium', (SELECT id FROM skill_categories WHERE name = 'Testing')),
  ('Jest', (SELECT id FROM skill_categories WHERE name = 'Testing')),
  ('Cypress', (SELECT id FROM skill_categories WHERE name = 'Testing')),
  ('Android', (SELECT id FROM skill_categories WHERE name = 'Mobile Development')),
  ('iOS', (SELECT id FROM skill_categories WHERE name = 'Mobile Development')),
  ('React Native', (SELECT id FROM skill_categories WHERE name = 'Mobile Development')),
  ('Flutter', (SELECT id FROM skill_categories WHERE name = 'Mobile Development')),
  ('Git', (SELECT id FROM skill_categories WHERE name = 'Tools')),
  ('Linux', (SELECT id FROM skill_categories WHERE name = 'Tools')),
  ('VS Code', (SELECT id FROM skill_categories WHERE name = 'Tools')),
  ('Postman', (SELECT id FROM skill_categories WHERE name = 'Tools')),
  ('Figma', (SELECT id FROM skill_categories WHERE name = 'Tools')),
  ('Communication', (SELECT id FROM skill_categories WHERE name = 'Soft Skills')),
  ('Teamwork', (SELECT id FROM skill_categories WHERE name = 'Soft Skills')),
  ('Problem Solving', (SELECT id FROM skill_categories WHERE name = 'Soft Skills')),
  ('Leadership', (SELECT id FROM skill_categories WHERE name = 'Soft Skills'))
ON CONFLICT (name) DO NOTHING;

-- Degrees
INSERT INTO degrees (name) VALUES
  ('B.Tech'),
  ('B.E.'),
  ('B.Sc.'),
  ('B.C.A.'),
  ('B.A.'),
  ('B.Com.'),
  ('M.Tech'),
  ('M.E.'),
  ('M.Sc.'),
  ('M.C.A.'),
  ('M.A.'),
  ('MBA'),
  ('Ph.D.'),
  ('Diploma'),
  ('B.Des.'),
  ('B.Arch.')
ON CONFLICT (name) DO NOTHING;

-- Specializations
INSERT INTO specializations (name) VALUES
  ('Computer Science'),
  ('Information Technology'),
  ('Electronics & Communication'),
  ('Electrical Engineering'),
  ('Mechanical Engineering'),
  ('Civil Engineering'),
  ('Data Science'),
  ('Artificial Intelligence'),
  ('Machine Learning'),
  ('Cyber Security'),
  ('Cloud Computing'),
  ('Software Engineering'),
  ('Information Systems'),
  ('Computer Applications'),
  ('Mathematics'),
  ('Physics'),
  ('Statistics')
ON CONFLICT (name) DO NOTHING;

-- Institutions
INSERT INTO institutions (name) VALUES
  ('Indian Institute of Technology Bombay'),
  ('Indian Institute of Technology Delhi'),
  ('Indian Institute of Technology Madras'),
  ('Indian Institute of Technology Kanpur'),
  ('Indian Institute of Technology Kharagpur'),
  ('Indian Institute of Technology Roorkee'),
  ('National Institute of Technology Trichy'),
  ('National Institute of Technology Surathkal'),
  ('National Institute of Technology Warangal'),
  ('Delhi Technological University'),
  ('Vellore Institute of Technology'),
  ('Birla Institute of Technology & Science Pilani'),
  ('SRM Institute of Science and Technology'),
  ('Amrita Vishwa Vidyapeetham'),
  ('Manipal Institute of Technology'),
  ('PSG College of Technology'),
  ('Thapar Institute of Engineering and Technology'),
  ('University of Delhi'),
  ('Jamia Millia Islamia'),
  ('Anna University'),
  ('PES University'),
  ('RV College of Engineering'),
  ('B.M.S. College of Engineering'),
  ('Christ University'),
  ('St. Josephs College')
ON CONFLICT (name) DO NOTHING;
